language: cpp
sudo: false
compiler: clang
dist: trusty
os:
  - linux
  - osx
cache:
  - ccache
  - apt
addons:
  apt:
    packages:
      - autoconf2.13
      - yasm
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf213 yasm; fi
before_script:
  - ./configure --debug --engine=spidermonkey
script:
  - make V= -k || make V= -k || true
  - ./deps/spidershim/scripts/run-tests.sh
branches:
  only:
    - master
notifications:
  email: true
env:
  global:
    - LANG="en_US.UTF-8"
