language: cpp
sudo: false
compiler:
  - gcc
  - clang
env:
  - BUILD_CONFIG=normal
  - BUILD_CONFIG=gczeal
dist: precise
os:
  - linux
  - osx
cache:
  - ccache
  - apt
addons:
  apt:
    packages:
      - autoconf2.13
      - yasm
      - gcc-4.8
      - g++-4.8
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf213 yasm; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$CC" == "gcc" ]; then export CC=gcc-4.8; export CXX=g++-4.8; fi
before_script:
  - ./configure --debug --engine=spidermonkey $(if [ "$BUILD_CONFIG" == "gczeal" ]; then echo "--enable-gczeal"; fi)
script:
  - make V= -k || true
  - if [ "$BUILD_CONFIG" == "gczeal" ]; then export JS_GC_MAX_ZEAL=1; fi
  - ./deps/spidershim/scripts/run-tests.sh
notifications:
  email: true
env:
  global:
    - LANG="en_US.UTF-8"
