language: cpp
sudo: required
compiler: clang
dist: trusty
os:
  - linux
  - osx
cache:
  - ccache
  - apt
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; else sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf213 yasm; else sudo apt-get install -y autoconf2.13 yasm zlib1g-dev; fi
before_script:
  - ./configure --debug --engine=spidermonkey
script:
  - make V= -k || make V= -k || true
  - for test in ./out/{Debug,Release}/{hello-world,value}; do "$test"; done
branches:
  only:
    - master
notifications:
  email: true
env:
  global:
    - LANG="en_US.UTF-8"
